trigger:
  branches:
    include:
    - refs/heads/main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      filePath: Hello.ps1
...
this is my edit on 29 may 2023